spring:
  application:
    name: urbanito

  datasource:
    url: jdbc:postgresql://localhost:5432/urbanito
    username: urbanito
    password: urbanito

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
